### ISSUE TITLE
우노 확장모드 업로드 에러

### ISSUE THREAD

**Issue by shkang770** [JeongJun-Lee/entry-offline#5]
아래와 같이 에러가 뜨네요
![엔트리확장모드_부저1](https://user-images.githubusercontent.com/22616432/128181162-9a50200d-a575-49a1-ae43-4dc64fa17e91.png)
![엔트리확장모드_부저2](https://user-images.githubusercontent.com/22616432/128181167-b556bffd-7869-42af-b43e-260aeb76e146.png)

**Comment by JeongJun-Lee** [comment]
안녕하세요? 해당 이슈는 오리지널 엔트리가 갖고 있는 문제이며, [이 곳](entrylabs/entryjs#2145)에서 이슈 트래킹 하실 수 있습니다.

**Comment by JeongJun-Lee** [comment]
엔트리팀에서 결국 아직까지도 수정을 안하셔서; 할 수 없이 다른 방식으로 제 쪽에서 수정하였고 해당 이슈는 46버전에서 해결됩니다.
